ATM_THRESHOLD = 0.05
AT_FORWARD_THRESHOLD = 1e-5
CALL_PUT_PARITY_THRESHOLD = 6

APPROXIMATION_THRESHOLD = 1e-10
APPROXIMATION_ITERATIONS = 250

PLOT_LOWER_THRESHOLD_MULTIPLIER = 0.5
PLOT_UPPER_THRESHOLD_MULTIPLIER = 1.5

INDICATOR_LINE_LINESTYLE = "-."
INDICATOR_LINE_ALPHA = 0.75  # Transparency
INDICATOR_LINE_LINEWIDTH = 1

PLOT_FONT_SIZE_MAIN = 12
PLOT_FONT_WEIGHT_MAIN = "bold"
PLOT_FONT_SIZE_LEGEND = 10

PLOT_LINE_WIDTH = 0.8
