class Pricing:
    # European
    def black_scholes(self):
        ...
    
    def black_scholes_merton(self):
        ...
    
    def black_76(self):
        ...

    def binomial_tree(self):
        ...

    def trinomial_tree(self):
        ...
    
    def monte_carlo(self):
        ...

    def bachelier(self):
        ...
