class InvalidOptionTypeException(Exception):
    ...

class InvalidOptionExerciseException(Exception):
    ...

class UnsupportedModelException(Exception):
    ...

class InvalidUnderlyingException(Exception):
    ...

class InvalidDirectionException(Exception):
    ...