class BinomialPricing:

    def universal_binomial_tree(self):
        ...

    def binomial_cox_ross_rubinstein(self):
        ...

    def binomial_cox_ross_rubinstein_drift(self):
        ...

    def binomial_rendleman_bartter(self):
        ...

    def binomial_leisen_reimer(self):
        ...

    def binomial_jarrow_rudd(self):
        ...

    def binomial_jarrow_rudd_risk_neutral(self):
        ...

    def binomial_tian(self):
        ...