class BjerksundStenslandPricing:

    def bjerksund_stensland_call_2002(self):
        ...

    def bjerksund_stensland_2002(self):
        ...

    def bjerksund_stensland_call_1993(self):
        ...

    def bjerksund_stensland_1993(self):
        ...